spring:
  datasource:
    url: jdbc:mysql://192.168.0.101:3306/test?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers:
      - 192.168.0.107:9091
      - 192.168.0.107:9092
      - 192.168.0.107:9093
    consumer:
      group-id: moveon
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis:
  type-aliases-package: cool.moveon.lmt.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true